# -*- coding: utf-8 -*-
require 'systemu'
require 'tempfile'
require 'colorize'
require 'coderay'

dirnames=Dir.pwd.split('/')
$basename = (dirnames[-1]=='hikis')? dirnames[-2] : dirnames[-1]
$latex_dir= 'latex_dir'

task :default do
  system 'rake -T'
end

desc "Githubのdirをsafariでopen"
task :github do
  status, stdout, stderr = systemu %q( git remote -v |grep origin )
  github_dir=stdout.match(/(.+):(.+) \(push\)/)[2]
  puts github_dir.blue
  system "open https://github.com/#{github_dir}"
end

desc ""
task :github do
  status, stdout, stderr = systemu %q( git remote -v |grep origin )
  github_dir=stdout.match(/(.+):(.+) \(push\)/)[2]
  puts github_dir.blue
  system "open https://github.com/#{github_dir}"
end

